function figure1=createfigure2(X1, Y1)
%CREATEFIGURE(X1, Y1)
% Ricardo ets acoraddo
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 25-Aug-2025 17:02:19

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1);

% Create xlabel
xlabel('$\frac{-b\pm\sqrt{\Delta}}{2a}$','FontSize',48,...
    'Interpreter','latex');

% Create title
title('$\frac{1}{2}$ Teste','Interpreter','latex');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Arial','FontSize',18);
grid